name: Trigger auto-onbord workflow

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - 'onboarding-*'

jobs:
  notify:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'onboarding-')
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: |
          curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Extract email from PR title
        id: extract_email_and_username
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          EMAIL="${TITLE#Onboarding }"
          USERNAME="${EMAIL%@*}"

          echo "email=$EMAIL" >> $GITHUB_OUTPUT
          echo "username=$USERNAME" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v44

      - name: Process user config file
        id: extract_alias
        run: |
          for file in ${{ steps.changed_files.outputs.added_files }}; do
            if [[ "$file" == configs/users/*.yaml ]]; then
              echo "Processing $file"
              ALIAS=$(yq eval '.username' "$file")
              echo "alias=$ALIAS" >> $GITHUB_OUTPUT
            fi
          done

      - name: Debug outputs
        run: |
          echo "Alias: ${{ steps.extract_alias.outputs.alias }}"
          echo "Email: ${{ steps.extract_email_and_username.outputs.email }}"
          echo "Username: ${{ steps.extract_email_and_username.outputs.username }}"

      - name: Call workflow in auto-onboard
        uses: actions/github-script@v7
        with:
          script: |
            const res = await github.rest.actions.createWorkflowDispatch({
              owner: 'treezio',
              repo: 'auto-onboard',
              workflow_id: 'auto-onboard.yaml',
              ref: 'main',
              inputs: {
                alias: "${{ steps.extract_alias.outputs.alias }}",
                email: "${{ steps.extract_email_and_username.outputs.email }}",
                username: "${{ steps.extract_email_and_username.outputs.username }}"
              }
            });

            console.log(`Dispatched target workflow: ${res.status}`);
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}